SOCIAL_GRAPH = {
    #阿比一家
    "Abigail": {
        "Pierre": 0.25,
        "Caroline": 0.2,
        "Sam": 0.18,
        "Sebastian":0.15,
    },
    "Caroline": {
        "Pierre": 0.08, 
        "Abigail": 0.18,
        "Jordi":0.15,
        "Robin":0.3,
        "Marnie":0.3
    },
    "Pierre": {
        "Caroline": 0.08,
        "Abigail": 0.23,
        "Lewis":0.29
    },
    #山姆一家
    "Sam": {
        "Abigail": 0.18,
        "Sebastian":0.1,
        "Jordi":0.15,
        "Vincent":0.25,
        "Kent":0.25,
        "Penny":0.19
    },
    "Vincent":{
        "Sam":0.08,
        "Kent":0.28,
        "Jordi":0.1,
        "Jas":0.05,
        "Penny":0.12,
        "Leo":0.18
    },
    "Jordi":{
        "Caroline":0.12,
        "Sam":0.18,
        "Vincent":0.28,
        "Kent":0.1,
        "Robin":0.3,
        "Marnie":0.3
    },
    "Kent":{
        "Sam":0.25,
        "Vincent":0.30,
        "Jordi":0.12
    },
    #384一家
    "Sebastian":{
        "Abigail":0.15,
        "Sam":0.1,
        "Robin":0.2,
    },
    "Robin":{
        "Sebastian":0.18,
        "Maru":0.18,
        "Demetrius":0.08,
        "Caroline":0.3,
        "Jordi":0.3,
        "Marnie":0.3,
        "Lewis":0.3
    },
    "Maru":{
        "Robin":0.18,
        "Demetrius":0.15,
        "Penny":0.2,
        "Sebastian":0.25,
        "Harvey":0.2
    },
    "Demetrius":{
        "Robin":0.08,
        "Maru":0.15,
        "Sebastian":0.25,
    },
    #玛尼一家
    "Marnie":{
        "Jas":0.25,
        "Shane":0.18,
        "Caroline":0.3,
        "Jordi":0.3,
        "Emily":0.3,
        "Robin":0.3,
        "Lewie":0.12,
    },
    "Shane":{
        "Jas":0.22,
        "Marnie":0.19,
        "Emily":0.2
    },
    "Jas":{
        "Marnie":0.12,
        "Shane":0.12,
        "Penny":0.18,
        "Vincent":0.05,
        "Leo":0.15
    },
    #潘妮一家
    "Penny":{
        "Sam":0.18,
        "Vincent":0.28,
        "Jas":0.28,
        "Maru":0.2,
        "Leo":0.28,
        "Pam":0.22
    },
    "Pam":{
        "Penny":0.21,
        "Gus":0.22
    },
    "Leo":{
        "Penny":0.2,
        "Jas":0.09,
        "Vincent":0.12,
        "Willy":0.25,
        "Linus":0.1
    },
    "Linus":{
        "Leo":0.12,
        "Wizard":0.2
    },
    "Wizard":{
        "Linus":0.22
    },
    "Willy":{
        "Elliott":0.22,
        "Gus":0.25,
        "Lewis":0.2
    },
    "Elliott":{
        "Willy":0.22,
        "Leah":0.18
    },
    "Leah":{
        "Elliot":0.18
    },
    "Alex":{
        "Haley":0.15,
        "George":0.22,
        "Evelyn":0.2
    },
    "George":{
        "Evelyn":0.06,
        "Alex":0.22
    },
    "Evelyn":{
        "Alex":0.2,
        "George":0.08
    },
    "Haley":{
        "Emily":0.22,
        "Alex":0.16
    },
    "Emily":{
        "Haley":0.22,
        "Gus":0.28,
        "Shane":0.2,
        "Client":0.28,
        "Sandy":0.13,
        "Robin":0.3,
        "Marnie":0.3,
        "Jordi":0.3,
        "Caroline":0.3
    },
    "Gus":{
        "Emily":0.25,
        "Pam":0.22
    },
    "Lewis":{
        "Damon":0.25,
        "Marnie":0.1,
        "Willy":0.2,
        "Client":0.22,
        "Robin":0.3
    },
    "Client":{
        "Emily":0.25,
        "Gus":0.23
    },
    "Sandy":{
        "Emily":0.12
    },
    "Damon": {
        "Lewis": 0.25
    }
}